{% set name = "jupysql" %}
{% set version = "0.10.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupysql-{{ version }}.tar.gz
  sha256: b727ea27074febc9be27e477b887ec04ef8d342f5ee1aed5c797f7e926936df8

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - ploomber-extension
    - jupysql-plugin >=0.4.2
    - psutil
    - python >=3.7
    - prettytable
    - ipython >=1.0
    - sqlalchemy
    - sqlparse
    - ipython_genutils >=0.1.0
    - sqlglot >=11.3.7
    - jinja2
    - ploomber-core >=0.2.7
    - importlib-metadata

test:
  imports:
    - sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ploomber/jupysql
  summary: Better SQL in Jupyter
  dev_url: https://github.com/ploomber/jupysql
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yafimvo
    - idomic
    - edublancas
    - sterlinm
    - neelasha23
