{% set name = "jupysql" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupysql-{{ version }}.tar.gz
  sha256: 596200126198640c65e7e52069f4413d46b0091a2f53dcc5b818d5b026e798cb

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - prettytable
    - ipython >=1.0
    - sqlalchemy <2
    - sqlparse
    - ipython_genutils >=0.1.0
    - sqlglot >=11.3.7
    - jinja2
    - ploomber-core >=0.2.7
    - importlib-metadata

test:
  imports:
    - sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ploomber/jupysql
  summary: Better SQL in Jupyter
  dev_url: https://github.com/ploomber/jupysql
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yafimvo
    - idomic
    - edublancas
    - sterlinm
