{% set name = "jupysql" %}
{% set version = "0.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/jupysql-{{ version }}.tar.gz
  sha256: 560012c8af82103f9e0afba00c6b444976737d05f101ff5cb104837f61c524c1

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - psutil
    - python >=3.7
    - prettytable
    - ipython >=1.0
    - sqlalchemy
    - sqlparse
    - ipython_genutils >=0.1.0
    - sqlglot
    - jinja2
    - ploomber-core >=0.2.7
    - importlib-metadata

test:
  imports:
    - sql
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ploomber/jupysql
  summary: Better SQL in Jupyter
  dev_url: https://github.com/ploomber/jupysql
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - yafimvo
    - idomic
    - edublancas
    - sterlinm
    - neelasha23
